name: kaia-safe-react production deploy workflow
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_PROD }}
          role-session-name: SessionForKaiaActions
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile && yarn after-install
          cp ./override/utils.js ./node_modules/@safe-global/safe-gateway-typescript-sdk/dist

      - name: Build static files
        env:
          NEXT_PUBLIC_GATEWAY_URL_PRODUCTION: ${{ secrets.NEXT_PUBLIC_GATEWAY_URL_PROD }}
          NEXT_PUBLIC_IS_PRODUCTION: ${{ secrets.NEXT_PUBLIC_IS_PRODUCTION }}
          NEXT_PUBLIC_IS_OFFICIAL_HOST: ${{ secrets.NEXT_PUBLIC_IS_OFFICIAL_HOST }}
          NEXT_PUBLIC_WC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WC_PROJECT_ID_PROD }}
          NEXT_PUBLIC_BANNER_API: ${{ secrets.NEXT_PUBLIC_BANNER_API }}
        run: yarn build

      - name: Sync to S3 bucket and validation cloudfront
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
          CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID_PROD }}
        run: |
          aws s3 sync ./out $S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
